name: AWS IAM Role Checker

on:
  workflow_dispatch:  # manual trigger

jobs:
  check-iam-roles:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Read Config File
        id: read-config
        run: |
          echo "Reading configuration from config/config.yml..."
          AWS_ACCOUNTS=$(yq '.inputs.aws_accounts' config/config.yml | tr -d '"')
          AWS_REGIONS=$(yq '.inputs.aws_regions' config/config.yml | tr -d '"')
          ROLE_NAMES=$(yq '.inputs.role_names' config/config.yml | tr -d '"')

          echo "aws_accounts=$AWS_ACCOUNTS" >> $GITHUB_ENV
          echo "aws_regions=$AWS_REGIONS" >> $GITHUB_ENV
          echo "role_names=$ROLE_NAMES" >> $GITHUB_ENV

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::851321632855:role/githubaction-aws-connectivity-role  # update this once for OIDC
          aws-region: us-east-1

      - name: Check IAM Roles Across Accounts and Regions
        run: |
          IFS=',' read -ra ACCOUNT_IDS <<< "$aws_accounts"
          IFS=',' read -ra REGION_LIST <<< "$aws_regions"
          IFS=',' read -ra ROLE_NAMES <<< "$role_names"

          for ACCOUNT in "${ACCOUNT_IDS[@]}"; do
            echo "==============================="
            echo "🔍 Checking Account: $ACCOUNT"
            echo "==============================="

            for REGION in "${REGION_LIST[@]}"; do
              echo "➡️ Region: $REGION"
              
              for ROLE in "${ROLE_NAMES[@]}"; do
                echo "  Checking IAM Role: $ROLE ..."
                if aws iam get-role --role-name "$ROLE" --region "$REGION" >/dev/null 2>&1; then
                  echo "  ✅ Role '$ROLE' exists in $ACCOUNT ($REGION)"
                else
                  echo "  ❌ Role '$ROLE' not found in $ACCOUNT ($REGION)"
                fi
              done
              echo ""
            done
          done

      - name: Summary
        run: echo "✅ IAM Role check completed successfully!"
